name: macOS

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Install CMake 3.22
        # gflags 2.2.2 uses cmake 3.0, and the latest cmake doesn't support cmake that <= 3.5
        # To pass the tests, install the specified cmake
        run: |
          set -e
          curl -sL https://cmake.org/files/v3.22/cmake-3.22.0-Darwin-x86_64.tar.gz | tar -xzv
          echo "$(pwd)/cmake-3.22.0-Darwin-x86_64/CMake.app/Contents/bin" >> $GITHUB_PATH
          cmake --version

      - name: Tests
        run: |
          ./scripts/test-unix.sh

