name: Windows

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Tests
        run: |
          cmake -DXREPO_PACKAGE_VERBOSE=ON example
          cmake --build .

